config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'
  resources :users, only: [:create, :show, :update]

  get '/search' =>'activities#search'
  get '/directions' =>'activities#direction'

  get '/register' => 'users#new', as: :register
  get '/logout' => 'sessions#destroy', as: :logout
  get '/login' => 'sessions#new', as: :login
  post '/session_create' => 'sessions#create', as: :session_create

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get '/edit' => 'users#edit'

  patch '/users/:id' => 'users#update'
  patch 'friendships/:id' => 'friendships#accept'
  delete 'friendships/:id' => 'friendships#reject'

resources :friendships, only: [:create, :update, :destroy]
resources :votes, only: [:create]
resources :activities, only: [:new, :create, :show]

resources :activities, only: [:show, :new, :create ]

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

end

app/views/homepage/index.html.erb
<br>
<div class="row">
  <div class="large-6 small-12 large-centered small-centered columns">
    <p class="interests">What are you looking to do today? </p>
  </div>
</div>

<div class="row">
  <div class="large-3 small-3 columns">

     <a id="activity-button" href="activities/new?data-type=active" class="button tiny">Do</a>
  </div>

  <div class="large-3 small-3 columns">
     <a id="activity-button" href="activities/new?data-type=restaurants" class="button tiny">Eat</a>

  </div>

  <div class="large-3 small-3 columns">
    <a id="activity-button" href="activities/new?data-type=arts" class="button tiny">See</a>
  </div>

  <div id="item_button" class="large-3 small-3 columns">
    <a id="activity-button" href="activities/new?data-type=bars" class="button tiny"> Drink</a>
  </div>
</div>


<div class="row">
  <div class="large-6 small-12 large-centered small-centered columns">
      <%= link_to image_tag("park2.png"), new_activity_path({:'data-type' => 'active'})%>
  </div>
</div>

<div id="row">
  <div id="logo" class="large-6 small-12 large-centered small-centered columns">
      <%= link_to image_tag("nice_logo6.png"), new_activity_path %>
  </div>
</div>

<div class="row">
  <div class="large-6 small-12 large-centered small-centered columns">
     <%= link_to image_tag("do1.png"), new_activity_path({:'data-type' => 'arts'}) %>
  </div>
</div>