config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'
  resources :users, only: [:create, :show, :update]

  get '/search' =>'activities#search'
  get '/directions' =>'activities#direction'

  get '/register' => 'users#new', as: :register
  get '/logout' => 'sessions#destroy', as: :logout
  get '/login' => 'sessions#new', as: :login
  post '/session_create' => 'sessions#create', as: :session_create

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get '/edit' => 'users#edit'

  patch '/users/:id' => 'users#update'
  patch 'friendships/:id' => 'friendships#accept'
  delete 'friendships/:id' => 'friendships#reject'

resources :friendships, only: [:create, :update, :destroy]
resources :votes, only: [:create]
resources :activities, only: [:new, :create, :show]

resources :activities, only: [:show, :new, :create ]

end

app/models/Activity.rb
# Your file names should be lower case for these models
class Activity < ActiveRecord::Base
  validates :location, :title, presence: true
  validates :creator_id, :friend_id, presence: true
  belongs_to :creator, class_name: 'User'
  belongs_to :friend, class_name: 'User'
  has_many :votes
  # after_create :send_activity_email

  def self.parse_businesses(possible_businesses)
    possible_businesses.map {|business| [business["title"], business["alias"]]}
  end

  def not_yet_rated(user)
    self.votes.where(user_id: user.id).empty?
  end

  def send_activity_email
    ActivityMailer.activity_email(self).deliver_now
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
    #It's preferable to have an ensure_login or similar on application controller for 
    # new, create, update, destroy, then do skip_before_login where you have exceptions. 
    # Otherwise you have to repeat this check in many places, and have to remember to place it 
    # everywhere it's needed.

    if logged_in?
      @users = (current_user.friends).map{|user| [user.username, user.id, {:'data-lat' => user.lat, :'data-long' => user.long, :'data-id' => user.id, class: "user-#{user.id}"}]}
      @category_filter = Activity.parse_businesses(categories)
    else
      redirect_to login_path
    end
  end

  def create
    @friend= User.find(params[:friend].to_i)
    destination = business(Yelp.client.search_by_coordinates(midpoint_location, search_parameters))
    #Is destination guaranteed to be non-nil here?
    coords = destination.location.coordinate
    address = destination.location.display_address.join(", ")
    @activity = Activity.new(location: address, title: destination.name, creator_id: current_user.id, friend_id: params[:friend].to_i, lat: coords.latitude, long: coords.longitude)
    #Save! will throw an error on failure so your else will never be reached
    if @activity.save!
      @friend = User.find(@activity.friend_id)
      render :show, layout:false
    else
      status 400
    end
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def direction
    @origin = { lat: params["data-origin-lat"], lng: params["data-origin-long"] }
    @destination = { lat: params["data-destination-lat"], lng: params["data-destination-long"] }
  end

  private

  def activity_params
    params.permit(:activity, :midlat, :midlong)
  end

  def yelp
    File.read("vendor/assets/javascripts/categories.json")
  end

  def categories
    # Is a hard-coded array the right place for your activity types?
    params[:'data-type'] = ['active', 'restaurants', 'arts', 'bars'].sample unless params[:'data-type']
    JSON.parse(yelp).select{ |business| business["parents"].include?(params[:'data-type'])}
  end

  def business(search_results)
    search_results.businesses.select { |business| !business.is_closed }.sample
  end

  def search_parameters
    { term: params[:activity], radius_filter: 800, rating: 3}
  end

  def midpoint_location
    {latitude: params[:midlat], longitude: params[:midlong]}
  end
end

app/views/activities/direction.html.erb
<br><br>
<div class="row">
  <div class="large-6 small-12 large-centered small-centered columns">
    <div id="floating-panel">
      <b>Mode of Travel:</b>
      <br>
      <select id="mode">
        <option value="SELECT">Select one</option>
        <option value="DRIVING">Driving</option>
        <option value="WALKING">Walking</option>
        <option value="BICYCLING">Bicycling</option>
        <option value="TRANSIT">Transit</option>
      </select>
    </div>
    <div id="origin"></div>
    <div id="destination"></div>
  </div>
</div>

<div class="row">
  <div class="large-6 small-12 large-centered small-centered columns">
    <div id="map-image", style="width: 100%; height: 500px;"></div>
    <div id="right-panel"></div>
    <div class="origin" data-origin-lat="<%=@origin[:lat]%>" data-origin-lng="<%=@origin[:lng]%>"></div>
    <div class="destination" data-destination-lat="<%=@destination[:lat]%>" data-destination-lng="<%=@destination[:lng]%>"></div>
  </div>
</div>
<br><br>

app/views/activities/new.html.erb
<div class="page-container">
  <div class="content">
    <div class="create-activity">
      <br>
      <div class="row">
        <div class="large-6 small-6 large-centered small-centered columns">
          <p class="error-message"></p>
        </div>
      </div>
      <div class="row">
        <!-- <div class="large-12 small-12 large-centered small-centered columns"> -->
          <div id="activity-new" class="title-area">What's the Middle Ground?</div>
        </div>
      </div>
      <br>
      <div class="row">

        <div class="large-4 small-8 large-centered small-centered columns">
          <div id="new-activity-form-container">
            <div class="form_fields">
              <%= form_tag ("/activities") %>

              <p><%= label_tag "Who are you meeting?" %></p>
              <p><%= select_tag(:user, options_for_select(@users)) %></p>
              <p><%= label_tag "Activity:" %></p>
              <p><%= select_tag(:activity, options_for_select(@category_filter))%></p>
              <p><%= submit_tag 'Find us the MiddleGround!' %></p>
            </div>
          <div>
        </div>
          <br>

      </div>
    </div>
    <div class="row">
      <section class="large-6 small-8 large-centered small-centered columns" id="user-location">
        <article class="map-container">
        </article>
      </section>
    </div>
    <br>
    <!-- <div class="row"> -->
      <!-- <div class="large-6 small-12 large-centered small-centered columns"> -->
        <div class="yelp-logo">
          <span><%= image_tag "yelp-logo-large.png" %></span>
        </div>
      <!-- </div> -->
    <!-- </div> -->
    <br><br>
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<div class="activity-container">
  <div class="content">
    <div class="activity-information-container">
      <div class="details-container">
        <br><br>
        <div class="row">
          <div class="large-6 small-12 large-centered small-centered columns">
          <p>You are going to <b><%= @activity.title %></b> with <%=@friend.username%></p>

          <p><strong><%=@activity.location%></strong></p>
        </div>
      </div>
      <div class="send-request-form">
      </div>
      <div class="map-directions-container">
        <div class="row">
          <div class="large-6 small-12 large-centered small-centered columns">
            <%= link_to "<button>Get Directions</button>".html_safe, directions_path({:'data-destination-lat' => @activity.lat, :'data-destination-long' => @activity.long,  :'data-origin-lat' => current_user.lat, :'data-origin-long' => current_user.long}), :class => "destination"%>
          </div>
          <br>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="large-6 small-12 large-centered small-centered columns">
    <div id="user-location" data-friend-lat="<%=@friend.lat%>" data-friend-long="<%=@friend.long%>">
      <article class="destination" data-destination-lat= '<%=@activity.lat%>', data-destination-long= '<%=@activity.long%>'></article>
    </div>
  </div>
</div>
<br>
<div class="row">
  <div class="large-6 small-12 large-centered small-centered columns">
    <div class="yelp-logo">
      <span><%= image_tag "yelp-logo-large.png" %></span>
    </div>
  </div>
</div>
<br><br>